---
name: Action
"on":
  push:

env:
  DATA_DIR: /var/run/datadir
jobs:
  action:
    runs-on: ubuntu-latest
    services:
      nginx:
        image: nginx
        ports:
          - 8080:80
        volumes:
          - /var/run/datadir:/usr/share/nginx

    steps:
      - uses: actions/cache@v3
        id: cache
        with:
          path: /data
          key: test-${{ runner.os }}-${{ github.run_id }}
          restore-keys: |
            test-${{ runner.os }}

      - run: |
          cat /etc/passwd
          id "$(whoami)"
          cat /etc/sub{uid,gid}
          sudo ls -la ${{ env.DATA_DIR }}
          echo "Hi from Action! cached: ${{ steps.cache.outputs.cache-hit }}" \
            | sudo tee ${{ env.DATA_DIR }}/index.html
          curl localhost:8080
